# docker-compose.yml for Athena Web Quiz
# TODO: Complete this file to orchestrate the Flask app, PostgreSQL database, and NGINX reverse proxy
# 1. Define a service for the Flask app
# 2. Define a service for PostgreSQL with environment variables for database configuration
# 3. Define a service for NGINX as a reverse proxy
# 4. Set up volumes for persistent database storage
# 5. Configure networks for communication between services
# Example:
services:
  flask_app:
    build: .
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
       FLASK_APP: ${FLASK_APP}
       FLASK_ENV: ${FLASK_ENV}
       SECRET_KEY: ${SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - athena_network
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER:{POSTGRES_USER}
      - POSTGRES_PASSWORD:{POSTGRES_PASSWORD}
      - POSTGRES_DB:{POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - athena_network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert.pme:/etc/nginx/cert.pem
      - ./nginx/key.pem:/etc/nginx/key.pem
    depends_on:
      - flask_app
volumes:
  db_data:

networks:
  athena_network:
  driver: bridge
