# Minimal CI workflow for Flask + Postgres
# See: https://docs.github.com/en/actions/guides/building-and-testing-python
name: CI Test

on:
  pull_request:
    branches:
      - main
      - dev
      - 'feature/**'
  push:
    branches:
      - main
      - dev
      - 'feature/**'

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres_user
          POSTGRES_PASSWORD: postgres_pass
          POSTGRES_DB: postgres_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DATABASE_URL: ${DATABASE_URL}
    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "FLASK_APP=${{ vars.FLASK_APP }}" >> .env
          echo "FLASK_ENV=${{ vars.FLASK_ENV }}" >> .env
          echo "DATABASE_URL=postgresql://${{ vars.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ vars.POSTGRES_DB }}" >> .env
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r app/requirements.txt
          pip install flake8
        
      - name: Run lint
        run: |
          flake8 app tests
          
      - name: Show Docker logs
        run: docker compose logs flask_app

      - name: Wait for services to start and to be healthy
        uses: jaracogmbh/docker-compose-health-check-action@v1.0.0
        with:
         max-retries: 10 
         retry-interval: 10
         compose-file: "docker-compose.yml" 
         skip-exited: "true"
         skip-no-healthcheck: "true"

      - name: Run tests
        run: pytest tests/ -v
